// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,1
/// 
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2l49Yk7ghoJl7EWIRLPXpspAHW__Qj9c',
    appId: '1:21127206712:web:YOUR_WEB_APP_ID',
    messagingSenderId: '21127206712',
    projectId: 'bank-a-plus',
    authDomain: 'bank-a-plus.firebaseapp.com',
    storageBucket: 'bank-a-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2l49Yk7ghoJl7EWIRLPXpspAHW__Qj9c',
    appId: '1:21127206712:android:792cb9d97ed73cb4f5d3cd',
    messagingSenderId: '21127206712',
    projectId: 'bank-a-plus',
    storageBucket: 'bank-a-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2l49Yk7ghoJl7EWIRLPXpspAHW__Qj9c',
    appId: '1:21127206712:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '21127206712',
    projectId: 'bank-a-plus',
    storageBucket: 'bank-a-plus.firebasestorage.app',
    iosBundleId: 'com.example.bankAPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2l49Yk7ghoJl7EWIRLPXpspAHW__Qj9c',
    appId: '1:21127206712:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '21127206712',
    projectId: 'bank-a-plus',
    storageBucket: 'bank-a-plus.firebasestorage.app',
    iosBundleId: 'com.example.bankAPlus',
  );
}
